### PR TITLE
Cache Node modules between deploys

### PR DESCRIPTION
**Pull request by wearhere**

### CODE REVIEW

**Comment by wearhere** [comment]
With just a little cleanup, yeah.

**Comment by bradvogel** [comment]
Does this mean we should do regular rolling deploys instead of Rolling With Batch?

**Comment by wearhere** [comment]
If we can tolerate a decrease in capacity during the deploy, then yes it would be better to switch to regular rolling deploys.

**Comment by bradvogel** [comment]
Yeah, should be fine. We can also switch to smaller batches, so it swaps out a single instance at a time.

**Pull request merged**
